# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              Building Bridges (Quadram Institute Bioscience)
description:        networking and training activities to strengthen relationships between the Quadram Institute Bioscience and EU partners

# Site subpath, e.g. /blog ## TODO
baseurl:            "/octo-test/"

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url:                ""

# Site logo, image or text
logo:                # e.g. logo.png, upload logo image file to /assets/img/ folder
logo_text:          Building Bridges      # if the above "logo:" image variable  is not set, this text logo is displayed instead

# Author settings, displayed on about page
author:
    name:           Lisa Marchioretto
    bio:            Hi, I'm Lisa, a programme manager and EU enthusiast.
    email:          lisa.marchioretto@quadram.ac.uk


# Social share buttons
twitter_username:   LisaMarchioret1
github_username:    marchiol

# Site background color
template:           light       # light or dark

# Default header image settings
header:
    image:          header.jpg  # upload your header image to /assets/posts/ folder
    align:          center      # top, center or bottom
    text:           light        # light or dark

# Default footer image settings
footer:
    image:          footer.jpg  # upload your header image to /assets/posts/ folder
    align:          center      #top, center or bottom
    text:           light       # light or dark
    copyright:      Template by <a href="https://unbound.studio/">Unbound Studio</a>.

# Post settings
post:
    dropcap: true

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      # 7865

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Google maps API key, get your key here: https://developers.google.com/maps/documentation/javascript/get-api-key
google_maps_api_key: 

# Number of posts displayed on blog page
paginate:           5

# Path to post content assets directory i.e post images, pdfs etc
post_assets:        /assets/posts/

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed
